/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package backups;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * 
 */
public class FrmDades extends javax.swing.JDialog {
    private FrameApplicationInit jfrm;

    /**
     * Creates new form FrmDades
     * @param parent AppUB4
     * @param modal boolean, bloqueja/desbloqueja la finestra de registre mentre el diàleg està obert
     * @param controlador Controller, controlador
     */
    public FrmDades(FrameApplicationInit parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.jfrm = parent;
        this.setLocationRelativeTo(parent);
        this.setTitle("rute data");
        this.btnAcceptar.setEnabled(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCamiDades = new javax.swing.JLabel();
        txtCamiDades = new javax.swing.JTextField();
        btnAcceptar = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelCamiDades.setText("Select the rute of the file:");

        txtCamiDades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCamiDadesKeyReleased(evt);
            }
        });

        btnAcceptar.setText("Accept");
        btnAcceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptarActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnSeleccionar.setText("Select");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(labelCamiDades)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCamiDades, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnAcceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit)))
                .addGap(18, 18, 18)
                .addComponent(btnSeleccionar)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCamiDades)
                    .addComponent(txtCamiDades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcceptar)
                    .addComponent(btnExit))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Activa el botó Acceptar si el camp de text no està buit
     * @param evt KeyEvent
     */
    private void txtCamiDadesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamiDadesKeyReleased
        if(!this.txtCamiDades.getText().isEmpty()){
            this.btnAcceptar.setEnabled(true);
        }else{
            this.btnAcceptar.setEnabled(false);
        }
    }//GEN-LAST:event_txtCamiDadesKeyReleased

    /**
     * Acció que es fa en pressionar el botó Acceptar. Guarda les dades al fitxer seleccionat i torna el control a la 
     * finestra anterior
     * @param evt ActionEvent
     */
    private void btnAcceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptarActionPerformed
        try{
            this.jfrm.setRuteDataBBDD(this.txtCamiDades.getText());
            this.dispose();
        }catch(Exception error){
            JOptionPane.showMessageDialog(this, error.getMessage(), "An error ocurred", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAcceptarActionPerformed

    /**
     * Acció que es fa en pressionar el botó Cancelar. Torna el control a la finestra anterior
     * @param evt ActionEvent
     */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * Acció que es fa en pressionar el botó Seleccionar. Selecciona un fitxer ja existent
     * @param evt ActionEvent
     */
    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        File fitxer;
        JFileChooser seleccio = new JFileChooser();
        int resultat = seleccio.showOpenDialog(this);
        if(resultat == JFileChooser.APPROVE_OPTION){
            fitxer = seleccio.getSelectedFile();
            this.txtCamiDades.setText(fitxer.toString());
            this.btnAcceptar.setEnabled(true);
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptar;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel labelCamiDades;
    private javax.swing.JTextField txtCamiDades;
    // End of variables declaration//GEN-END:variables
}