/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package backups;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;
import model.Client;
import model.NoteClient;

/**
 *
 * @author Glenius
 */
public class JDDeleteComments extends javax.swing.JDialog {

    Client client;
    
    /**
     * Creates new form JDDeleteComments
     */
    public JDDeleteComments(java.awt.Frame parent, boolean modal, Client client) {
        super(parent, modal);
        initComponents();
        this.setDefaultLookAndFeelDecorated(true);
        this.setLocationRelativeTo(parent);
        this.client = client;
        
        this.jLabelClient.setText("comments client " + this.client.getName());
        //this.jListComments.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        this.updateJList();
        this.setVisible(true);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDelete = new javax.swing.JButton();
        btnCloseWindow = new javax.swing.JButton();
        jLabelClient = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListComments = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnDelete.setText("Delete selected comments");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCloseWindow.setText("Close window");
        btnCloseWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseWindowActionPerformed(evt);
            }
        });

        jLabelClient.setText("Comments client selected:");

        jScrollPane1.setViewportView(jListComments);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCloseWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete)))
                    .addComponent(jLabelClient, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelClient, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCloseWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseWindowActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseWindowActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        int[] select = this.jListComments.getSelectedIndices();
        
        for(int i=0, index;i<select.length;++i){
            this.client.deleteNote(select[i] -i);
        }
        
        this.updateJList();
    }//GEN-LAST:event_btnDeleteActionPerformed


    private void updateJList(){
        ArrayList<NoteClient> notesClient = this.client.getNotesClient();
        
        if(notesClient.size() > 0){
            DefaultListModel<String> model = new DefaultListModel();
            
            model.clear();
            for (NoteClient note: notesClient){
                String string = note.toString();
                
                model.addElement(string);
            }
            this.jListComments.setModel(model);
            this.jListComments.setVisible(true);
        }else{
            this.emptyJList();
        }
    }
    
    private void emptyJList(){
        this.jListComments.clearSelection();
        this.jListComments.removeAll();
        DefaultListModel<String> model = new DefaultListModel();
        model.clear();
        this.jListComments.setModel(model);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseWindow;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabelClient;
    private javax.swing.JList<String> jListComments;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
